### ISSUE TITLE
Angular5 & Mangopay

### ISSUE THREAD

**Issue by remyblancke** [Mangopay/mangopay2-nodejs-sdk#107]
Hi, I'm starting with mangopay and I have a hard time finding good documentation, tutorial, example, integration of mangopay with angular 5. Can anyone help me?
Thank's in advance

**Comment by paulhristea** [comment]
Hello, @remyblancke!

Just letting you know, we're looking into this right now. At first impression, it seems like there will have to be made some changes in order to allow using the SDK from an Angular / browser environment, but after that it should be pretty straightforward:
* `npm install --save mangopay2-nodejs-sdk`
* `import * as mangopay from mangopay`
* Further usage as per documentations

Thanks for your patience!
Standby for more info.

**Comment by paulhristea** [comment]
Hello again.

My mistake! It is actually faulty logic to want to integrate the SDK directly into the Angular client. For example, where would you keep the Mangopay authorization credentials? Having them on the Angular client means they would be on the end-user's browser, which would break some privacy rules. You should integrate the SDK on the server-side of your app, and from Angular only use the Card Registration JS kit which you can find [here](https://github.com/Mangopay/cardregistration-js-kit).

Sorry about the mix-up!

**Comment by mickaelpois** [comment]
Hi @remyblancke,

@paulhristea is totally right, your Mangopay's calls logic has to be done on a server side, and not directly on a user browser (as it is already adviced for mobile apps), due to security needs, and simply as a good practice.

Please feel free to ask for some help if needed !

Mickaël
