### ISSUE TITLE
Version 1.10.0 not stable

### ISSUE THREAD

**Issue by Amassou** [Mangopay/mangopay2-nodejs-sdk#154]
Since version 1.10.0 all calls to API no longer work we have downgrade to version 1.8.0 in the meantime.
Any similar feedback ?

**Comment by mickaelpois** [comment]
Hello @Amassou,

Thanks for your feedback.

There's a significant update since 1.9.0 version on authentication: you must now use `clientApiKey` parameter name instead of `clientPassword` (see _Supported Options_ section on our README).

I guess you've maybe not seen this breaking change?
I've made it more readable on our last release note too.

Could you give me some feedback about that?

Mckaël

**Comment by Amassou** [comment]
After changing the key from clientPassword to clientApiKey everything seems to be working again.
We did not see the lines about the breaking change in the release note in the first place, now it has become quite noticeable ;) 
Thank you for everything

**Comment by mickaelpois** [comment]
You're very welcome @Amassou !
