### ISSUE TITLE
Users.createBankAccount

### ISSUE THREAD

**Issue by studiocodeur** [Mangopay/mangopay2-nodejs-sdk#245]
Hi, 

When i try to create a bankaccount for a user it fails. I think it might be something with the payload i'm sending. 

"bankAccount": {
      "UserId": "109476325",
      "OwnerName": "User name",
      "OwnerAddress": {
        "AddressLine1": "Adress 45",
        "AddressLine2": "",
        "City": "rotterdam",
        "PostalCode": "3103AK",
        "Country": "NL"
      },
      "IBAN": "BANKACCOUNTNR",
      "BIC": "BANK BIC",
      "Tag": "And a tag"
    }

What am i doing wrong?

**Comment by fredericdelordm** [comment]
Hello @studiocodeur,

Please look at this example [here](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/BankAccounts.js#L18). You are missing the "Details" object for IBAN and BIC.

Have a nice day

**Comment by studiocodeur** [comment]
Hi @fredericdelordm ,
Thank you for your response. 
And sorry to bother you again. 

But after running it with this payload i get no response 

 {
    "OwnerName": "Raoul Guillermo",
    "OwnerAddress": {
      "AddressLine1": "Stationsplein 45",
      "City": "rotterdam",
      "PostalCode": "3071KS",
      "Country": "NL"
    },
    "Details": {
      "IBAN": "FR7630004000031234567890143",
      "BIC": "BNPAFRPP"
    }
  }

**Comment by studiocodeur** [comment]
Do you perhaps have an example of the payload i need to run?

`

let payload = {
        bankAccount: {
          UserId: 108379078,
          OwnerName: `raoul guillermo`,
          OwnerAddress: {
            AddressLine1:`address`,
            City: `city`,
            PostalCode:`ziocode`,
            Country: `NL`,
          },
          Details: { IBAN: "FR7630004000031234567890143", BIC: "BNPAFRPP" },
        },
      };

api.Users.createBankAccount(
        108379078,
        payload,
        function (data) {
         console.log(data)
        }
      ).catch(function (err) {
        console.log(err.message)
      });`

**Comment by fredericdelordm** [comment]
As a good practice, it's always a good idea to have the MANGOPAY dashboard open while you developing.

Do you see the BankAccount for the User in the dashboard ?

Don't hesitate to look again the test that I have shared with you previously [here](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/master/test/services/BankAccounts.js), it's a good example for your feature.

Also, if you check the [documentation](https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e41_create-an-iban-bankaccount), you can see that the "Region" is missing in your "OwnerAddress" object.

You don't need to set the userId in the payload since you are passing it in the function `createBankAccount()`. You should get a bankAccount in response.

**Comment by studiocodeur** [comment]
Found it!
I needed to add Type: 'IBAN' to the payload. 
Also the details object was not needed. 

It's all working fine now. Thanks for your help.

**Comment by cedvdb** [comment]
The api allows invalid fields and the error is a 500.

```
    const details: bankAccount.IBANDetails = {
      Type: 'IBAN',
      OwnerName: data.ownerName,
      OwnerAddress: {
        AddressLine1: data.address.line1,
        AddressLine2: data.address.line2,
        City: data.address.city,
        Region: data.address.state,
        PostalCode: data.address.zip,
        Country: data.address.country as CountryISO,
      },
      IBAN: data.iban,
    };
    await this._api.Users.createBankAccount(data.userId, details);
```
