### ISSUE TITLE
TypeError: models.UserLegalPayer is not a constructor

### ISSUE THREAD

**Issue by MondayProgrammer** [Mangopay/mangopay2-nodejs-sdk#315]
Hi,

I just updated the SDK to the latest release, but using the new class [UserNaturalPayer](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/a4cdde29639e092b6faf42989733212b53dad51e/typings/index.d.ts#L439) invariably gives me the error : 
`TypeError: api.models.UserNaturalPayer is not a constructor`.

The following
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/a4cdde29639e092b6faf42989733212b53dad51e/typings/mangopay2-nodejs-sdk-tests.ts#L141-L146 also returns the error.

The same is true for [UserLegalOwner](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/a4cdde29639e092b6faf42989733212b53dad51e/typings/index.d.ts#L493), [UserNaturalPayer](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/a4cdde29639e092b6faf42989733212b53dad51e/typings/index.d.ts#L439) and [UserNaturalOwner](https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/a4cdde29639e092b6faf42989733212b53dad51e/typings/index.d.ts#L457).

Have a good day.

-----------------

Node v16.13.0
mangopay2-nodejs-sdk v1.29.0

**Comment by fredericdelordm** [comment]
Hello @MondayProgrammer,

We're looking into it.

**Comment by nkrmr** [comment]
Same error with the 1.29.1

ClientError: mangopayApi.models.UserNaturalPayer is not a constructor

**Comment by iulian03** [comment]
@nkrmr it looks like the issue was somewhere else, and we've made a patch for it. I will let you know as soon as it goes live, hopefully today. Sorry about the inconvenience.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/40763147/170442167-a5795c5e-1e08-461f-8e60-7c7970efb12c.png">

<img width="1861" alt="image" src="https://user-images.githubusercontent.com/40763147/170442191-c9a30a47-9034-44dc-a6fd-b656a2e3923f.png">

**Comment by iulian03** [comment]
@nkrmr hey! We've just released a patch. **1.29.2**

**Comment by MondayProgrammer** [comment]
The issue is fixed. Thanks!
