### ISSUE TITLE
Troubles creating direct payin

### ISSUE THREAD

**Issue by emilioriosvz** [Mangopay/mangopay2-nodejs-sdk#85]
Hello, I'm doing an integration with mangopay (using the sadbox) and I'm having troubles with the payin.

I'm using the example card (cardNumber = '4970100000000154', cardExpirationDate = '1019', cardCvx = '123')

I have this: 
```js
let params = {
    AuthorId: userId,
    CreditedWalletId: walletId,
    DebitedFunds: {
      Currency: currency,
      Amount: ammount
    },
    Fees: {
      Currency: currency,
      Amount: ammount
    },
    SecureModeReturnURL: 'http://test.com',
    CardId: cardId
}

api.PayIns.create(params)
    .then(payIn => resolve(payIn))
    .catch(err => reject(err))
```
The problem is that when I do de call, the method `create`  doesn't return nothing.
I'm doing something wrong?

**Comment by paulhristea** [comment]
Hello @emilioriosvz!

Because of how the request URLs are built, it is necessary to set certain sub-objects on the `PayIn` entity in order to have a successful response: its ExecutionType and its PaymentType.

Here is a snippet which demonstrates the correct way to declare and create a PayIn (adapt it to your own case by using the PaymentType and ExecutionType corresponding to your specific case):

```
            var payIn = new api.models.PayIn({
                CreditedWalletId: wallet.Id,
                AuthorId: user.Id,
                DebitedFunds: new api.models.Money({
                    Amount: 10000,
                    Currency: 'EUR'
                }),
                Fees: new api.models.Money({
                    Amount: 0,
                    Currency: 'EUR'
                }),
                PaymentType: 'CARD',
                PaymentDetails: new api.models.PayInPaymentDetailsCard({
                    CardType: 'CB_VISA_MASTERCARD'
                }),
                ExecutionType: 'WEB',
                ExecutionDetails: new api.models.PayInPaymentDetailsCard({
                    ReturnURL: 'https://test.com',
                    TemplateURL: 'https://TemplateURL.com',
                    SecureMode:  'DEFAULT',
                    Culture: 'fr'
                })
            });
            api.PayIns.create(payIn, callback)
```

Please try it this way, and reply with any other problems you encounter.
Thanks!

**Comment by emilioriosvz** [comment]
Perfect! Thanks a lot @paulhristea!
